wh="\033[1;37m"
bl="\033[1;90m"
rd="\033[1;31m"

echo -e "${wh}dddddddddddppddpp${bl}..........${wh}ppddppddddddddddd"
echo -e "${wh}ddddddddppdp${bl}...${rd}pppppddddppppp${bl}...${wh}pdppdddddddd"
echo -e "${wh}ddddddpdp${bl}..${rd}ppddddddddddddddddddpp${bl}..${wh}pdpdddddd"
echo -e "${wh}ddddpd${bl}...${rd}pddddddddddddddddddddddddp${bl}...${wh}dpdddd"
echo -e "${wh}dddpp${bl}..${rd}ppp${bl}.${rd}ppppdddddddddddddddddddddp${bl}..${wh}ppddd"
echo -e "${wh}ddp${bl}...${rd}pp${bl}..${rd}pddddddddddddddddddddddppppp${bl}...${wh}pdd"
echo -e "${wh}di${bl}...${rd}d${bl}...${rd}pddddddddddddddddddddddddd${bl}..${rd}pd${bl}...${wh}id"
echo -e "${wh}pp${bl}..${rd}pd${bl}....${rd}pppdpppppppdddddddddddddd${bl}...${rd}dp${bl}..${wh}pp"
echo -e "${wh}i${bl}..${rd}pddp${bl}.....................${rd}ppdppp${bl}....${rd}ddp${bl}..${wh}i"
echo -e "${wh}p${bl}..${rd}pdddp${bl}.............................${rd}pddp${bl}..${wh}p"
echo -e "${wh}p${bl}..${rd}pddddppp${bl}.......................${rd}ppddddp${bl}..${wh}p"
echo -e "${wh}p${bl}..${rd}pdddddpp${bl}.....${rd}p${bl}.........${rd}p${bl}......${rd}pddddddp${bl}..${wh}p"
echo -e "${wh}i${bl}...${rd}dddppp${bl}...................${rd}pppppdddddd${bl}...${wh}i"
echo -e "${wh}dp${bl}..........................${rd}pddddddddddp${bl}..${wh}pd"
echo -e "${wh}dpd${bl}.................${wh}pppp${bl}....${rd}pdddddddddp${bl}..${wh}dpd"
echo -e "${wh}ddpd${bl}...............${wh}pipiip${bl}...${rd}dddddddddp${bl}..${wh}dpdd"
echo -e "${wh}ddddpp${bl}...............${wh}pp${bl}.....${rd}dddddddp${bl}..${wh}ppdddd"
echo -e "${wh}dddddppp${bl}....................${rd}ddddpp${bl}..${wh}pppddddd"
echo -e "${wh}dddddddppd${bl}..................${rd}ppp${bl}...${wh}dppddddddd"
echo -e "${wh}ddddddddddppdp${bl}................${wh}pdppdddddddddd"
echo -e "${wh}ddddddddddddddppddddddddddddppdddddddddddddd"
